Qol improvements
pacstall/website pull request #177
Opened 2022-11-21 19:47 UTC by saenai255

2022-11-21 23:32 UTC, Henryws requested changes
Run prettier (`npx prettier --write client/src/*`), and supply the literal text `git` to git packages with an empty version.

2022-11-22 16:04 UTC, saenai255 commented
> and supply the literal text `git` to git packages with an empty version.

this is handled by the server already

2022-11-24 01:39 UTC, Henryws requested changes
Remove the repology title for packages

2022-11-29 23:33 UTC, Henryws approved these changes

2022-12-11 15:40 UTC, merged