feat(url-shortener): add url shortener
pacstall/website pull request #361
Opened 2023-05-01 17:07 UTC by saenai255

# Adds URL Shortener feature.

## Changes
 - Adds `gorm` dependency as the database ORM
 - Adds new required database connection environment variables - check compose file
 - Adds new table `pacstall.shortened_links` with the following structure:

| name       |      type          |  description    |
|------------|:------------------:|----------------:|
| id         |  uint              | primary key     |
| created_at |  timestamp         | audit           |
| updated_at |  timestamp         | audit           |
| deleted_at |  timestamp         | audit           |
| link_id    |  unique(string)    | url segment     |
| link       |  string            | redirect target |
| visits     |  uint              | no. of visits   |

![image](https://user-images.githubusercontent.com/16655260/235493361-9b0fd51c-5249-437b-b018-b54b694e1628.png)

## Notes
 - Make sure to test the new docker-compose file well before merging
 - After merging, consider adding a new entry in the new table having `link_id` equal to `install` and `link` equal to `https://github.com/pacstall/pacstall#installing` because I removed the link to the GitHub install page.

2023-05-02 11:32 UTC, saenai255 commented
Added matomo integration. Here's how the matomo events look:
![image](https://user-images.githubusercontent.com/16655260/235654543-452156da-b602-41ac-84a4-01a497f931b1.png)

2023-05-05 21:58 UTC, Henryws requested changes

2023-05-05 21:58 UTC, Henryws commented on server/server/api/url_shortener/url_shortener.go
> +
```suggestion
```

2023-05-05 21:59 UTC, Henryws requested changes

2023-05-05 21:59 UTC, Henryws commented on server/server/api/url_shortener/url_shortener.go
> +			log.Debug("Not tracking visit to [ShortenedLink (%s)] because of DoNotTrack flag", shortenedLink.LinkId)
```suggestion
```

2023-05-05 22:31 UTC, Henryws approved these changes

2023-05-05 22:31 UTC, merged