chore(locale): add `bn-IN` translations
pacstall/website pull request #399
Opened 2023-05-13 20:10 UTC by wizard-28

NOTE:
1. Word order needs to change for accurate translations in some places. Bengali's a [SOV language](https://en.wikipedia.org/wiki/Subject%E2%80%93object%E2%80%93verb_word_order) (Subject-Object-Verb) rather than SVO (Subject-Verb-Object) like English.
2. Support for Bengali numerals needs to be added.

2023-05-13 20:11 UTC, Henryws requested changes

2023-05-13 20:11 UTC, Henryws commented on client/src/locale/locale.ts
> +    'bn-IN': 'IN 🇮🇳',
Put this in alphabetical order.

2023-05-13 20:40 UTC, wizard-28 commented on client/src/locale/locale.ts
> +    'bn-IN': 'IN 🇮🇳',
Okay, it's sorted now (except English).

2024-07-03 15:08 UTC, Elsie19 approved these changes

2024-07-03 15:08 UTC, merged